# Generated by Django 2.1.7 on 2019-04-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.ImageField(default='DUMMY', upload_to='images/'),
            preserve_default=False,
        ),
    ]
