# Generated by Django 2.1.7 on 2019-04-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tweet_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='id',
            new_name='tweet_id',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
